version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: wifinder                    
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/wifinder
    volumes:
      - .:/app

volumes:
  postgres_data: